version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: postgresql/Dockerfile
    container_name: bls-postgres-db-container
    env_file: .env
    ports:
      - "5432:5432"

  postgrest:
    build:
      context: .
      dockerfile: postgrest/Dockerfile
    container_name: bls-postgrest-api
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres